version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
  proxy:
    image: nginx
    env_file: .env
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${APP_PORT_INT}:${APP_PORT_EXT}"
      - "${APP_ADMIN_PORT_INT}:${APP_ADMIN_PORT_EXT}"
    depends_on:
      - app